name: sudoku
description: A Sudoku game implemented in Flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  http: ^1.4.0
  firebase_core: ^3.13.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sudoku-459521-8ed444ef9272.json