// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqtoWRd0lxYMY65_dWTW8w79Hq8zgJw2w',
    appId: '1:933373330558:web:daf144a297ed401c84442f',
    messagingSenderId: '933373330558',
    projectId: 'sudoku-541e7',
    authDomain: 'sudoku-541e7.firebaseapp.com',
    storageBucket: 'sudoku-541e7.firebasestorage.app',
    measurementId: 'G-S6C8Y7RYFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDzpsQgrlBsD_beeYKSfDGCHEWbwBHtCs',
    appId: '1:933373330558:android:855fab5effea16d284442f',
    messagingSenderId: '933373330558',
    projectId: 'sudoku-541e7',
    storageBucket: 'sudoku-541e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVE79zajeujGhsDgFxFhWYxJQe6DMDqu4',
    appId: '1:933373330558:ios:19001decb562812d84442f',
    messagingSenderId: '933373330558',
    projectId: 'sudoku-541e7',
    storageBucket: 'sudoku-541e7.firebasestorage.app',
    iosBundleId: 'com.sycis.sudoku',
  );
}
